# Generated by Django 4.0.2 on 2022-03-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='number_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
