# Generated by Django 4.0.2 on 2022-02-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='professors',
            field=models.ManyToManyField(blank=True, null=True, to='teaching.Professor'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='modules',
            field=models.ManyToManyField(blank=True, null=True, to='teaching.Module'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='overall_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
