# Generated by Django 4.0.2 on 2022-03-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0002_professor_number_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='total_ratings_sum',
            field=models.FloatField(default=0.0),
        ),
    ]
