# Generated by Django 4.0.2 on 2022-02-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0002_alter_module_professors_alter_professor_modules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='value',
            field=models.FloatField(default=4),
        ),
    ]
